# Generated by Django 3.1.1 on 2023-06-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='man.png', upload_to='profile_pics'),
        ),
    ]
